"""Mermaid text for a ``GraphView`` and the three files ``vcp provenance graph`` writes.

- ``.html``: a page that renders the diagram in any browser; Mermaid comes from jsDelivr, pinned
  to one version and checked with Subresource Integrity, so the page needs network access.
- ``.md``: the diagram in a ```` ```mermaid ```` fence plus a legend (GitHub renders it).
- ``.mmd``: plain Mermaid for mermaid.live, Notion or any other Mermaid host.

Every file opens with ``MARKER``: the command replaces only files that open with it, so a
mistyped ``--out`` cannot overwrite somebody's notes. A drawing is never canonical evidence and
is refused inside the data root.
"""

from __future__ import annotations

import hashlib
import html
import os
from collections.abc import Callable, Iterable
from dataclasses import dataclass
from pathlib import Path

from vcp.core.errors import ValidationFailed
from vcp.provenance.render import ARTIFACT_KIND, GraphView, ViewEdge, ViewNode
from vcp.provenance.schema import EntityStatus

FORMATS = {".html": "html", ".md": "md", ".mmd": "mmd"}
MARKER = "generated by vcp provenance graph"
MERMAID_VERSION = "11.17.2"
MERMAID_URL = f"https://cdn.jsdelivr.net/npm/mermaid@{MERMAID_VERSION}/dist/mermaid.min.js"
MERMAID_SRI = "sha256-WB7X10vZBI0OOpE2OSfXLvIpQtdyJUayf3zCnjU5Drg="
# Mermaid's own defaults (maxEdges, maxTextSize); GitHub and mermaid.live refuse bigger diagrams.
DEFAULT_LIMITS = (500, 50_000)
# The html page raises both; these only keep a runaway page from hanging a browser tab.
HTML_LIMITS = (20_000, 5_000_000)
_MARKER_WINDOW = 4096
_HIDDEN_ROWS = 50
# How each writer opens its file (md, html, mmd); only such a file may be replaced.
_SIGNATURES = (f"<!-- {MARKER}", f"<!doctype html>\n<!-- {MARKER}", f"%% {MARKER}")

_SHAPES = {
    "dataset": ('[("', '")]'),
    "split": ('[/"', '"/]'),
    "run": ('["', '"]'),
    "fusion_run": ('{{"', '"}}'),
    "judgement": ('>"', '"]'),
    "submission": ('(["', '"])'),
    ARTIFACT_KIND: ('[["', '"]]'),
}
_DEFAULT_SHAPE = ('("', '")')
_ESCAPES = str.maketrans(
    {
        "#": "#35;",
        "%": "#37;",  # %%{...}%% anywhere in the text is a Mermaid directive
        "&": "#amp;",
        '"': "#quot;",
        "<": "#lt;",
        ">": "#gt;",
        "|": "#124;",
        "`": "#96;",
        "\n": " ",
        "\r": " ",
    }
)
_STATUS_CLASSES = (
    (EntityStatus.BROKEN, "st_broken"),
    (EntityStatus.STALE, "st_stale"),
    (EntityStatus.REVIEW, "st_review"),
)
_CLASS_DEFS = (
    "classDef st_broken fill:#fde8e6,stroke:#c0392b,color:#5c1a14",
    "classDef st_stale fill:#fff3d6,stroke:#b7791f,color:#5c3d0a",
    "classDef st_review fill:#e3edfb,stroke:#2b6cb0,color:#1a365d",
    "classDef backed stroke-width:3px",
)
_LEGEND = (
    ("cylinder", "dataset version: name, samples hash, sample count"),
    ("parallelogram", "split plan and its subsets"),
    ("rectangle", "run and its provenance grade (receipt > export > declared)"),
    ("hexagon", "fusion run"),
    ("flag", "judgement: pre-registration and verdict; arrows name the subsets it read"),
    ("stadium", "submission"),
    ("double-sided box", "artifacts of one kind, with counts"),
    ("thick arrow", "dataset evolution: the diff and how many samples changed"),
    ("thick border", "covered by a backup manifest"),
    ("BROKEN", "red: evidence is missing, corrupt or fails verification"),
    ("STALE", "amber: the dataset changed under it since it was made"),
    ("REVIEW", "blue: an unclassified change may affect it; a person decides"),
)
_FOLD_NOTE = (
    "The overview folds readings into run → judgement arrows and shows receipts, exports, "
    "caches, source audits, diffs and backups as grades, labels and borders; "
    "`--detail full` draws every entity except samples."
)


@dataclass(frozen=True)
class DocumentMeta:
    build: str
    backend: str
    index_hash: str
    head: str | None
    generated: str


@dataclass(frozen=True)
class Document:
    text: str
    oversize: bool  # beyond the limits of the Mermaid host this format is meant for


def group_id(name: str) -> str:
    return "g" + hashlib.sha256(name.encode("utf-8")).hexdigest()[:12]


def _text(value: str) -> str:
    return value.translate(_ESCAPES)


def _node_line(node: ViewNode) -> str:
    opening, closing = _SHAPES.get(node.kind, _DEFAULT_SHAPE)
    return f"{node.node_id}{opening}{'<br>'.join(_text(line) for line in node.label)}{closing}"


def _edge_line(edge: ViewEdge) -> str:
    arrow = "==>" if edge.thick else "-->"
    label = f'|"{_text(edge.label)}"|' if edge.label else ""
    return f"{edge.source} {arrow}{label} {edge.target}"


def to_mermaid(view: GraphView) -> str:
    lines = ["flowchart LR"]
    frames: dict[str, list[ViewNode]] = {}
    loose: list[ViewNode] = []
    for node in view.nodes:
        if node.group:
            frames.setdefault(node.group, []).append(node)
        else:
            loose.append(node)
    for name in sorted(frames):
        lines.append(f'  subgraph {group_id(name)}["{_text(name)}"]')
        # A frame with no arrow leaving it would otherwise fall back to top-down.
        lines.append("    direction LR")
        lines.extend(f"    {_node_line(node)}" for node in frames[name])
        lines.append("  end")
    lines.extend(f"  {_node_line(node)}" for node in loose)
    lines.extend(f"  {_edge_line(edge)}" for edge in view.edges)
    lines.extend(f"  {line}" for line in _CLASS_DEFS)
    for status, css in _STATUS_CLASSES:
        ids = sorted(node.node_id for node in view.nodes if node.status == status)
        if ids:
            lines.append(f"  class {','.join(ids)} {css}")
    backed = sorted(node.node_id for node in view.nodes if node.backed_up)
    if backed:
        lines.append(f"  class {','.join(backed)} backed")
    return "\n".join(lines) + "\n"


def _facts(view: GraphView, meta: DocumentMeta) -> list[tuple[str, str]]:
    return [
        ("vcp", meta.build),
        ("backend", meta.backend),
        ("index", meta.index_hash),
        ("scope", view.scope),
        ("head", meta.head or "worst over every head"),
        ("detail", view.detail),
        ("generated", meta.generated),
    ]


def _summary(view: GraphView) -> str:
    counts = view.counts
    return (
        f"{len(view.nodes)} nodes · {len(view.edges)} edges · "
        f"{view.folded} of {view.entities} entities not drawn on their own · "
        f"BROKEN {counts['BROKEN']} · STALE {counts['STALE']} · REVIEW {counts['REVIEW']}"
    )


def _hidden_rows(view: GraphView) -> Iterable[tuple[str, str, str]]:
    for record in view.hidden_alerts[:_HIDDEN_ROWS]:
        yield record.entity_id, record.status.value, " ".join(record.reason.split())


def _hidden_more(view: GraphView) -> int:
    return max(0, len(view.hidden_alerts) - _HIDDEN_ROWS)


def _md_cell(value: str) -> str:
    return " ".join(value.split()).replace("|", "\\|")


def _markdown(view: GraphView, diagram: str, meta: DocumentMeta) -> str:
    facts = " · ".join(f"{key} `{value.replace('`', "'")}`" for key, value in _facts(view, meta))
    lines = [
        f"<!-- {MARKER}; regenerate it with the same command instead of editing it -->",
        "",
        "# Provenance graph",
        "",
        facts,
        "",
        _summary(view),
        "",
        "```mermaid",
        diagram.rstrip("\n"),
        "```",
        "",
        "| mark | meaning |",
        "|---|---|",
        *(f"| {mark} | {meaning} |" for mark, meaning in _LEGEND),
        "",
        _FOLD_NOTE,
    ]
    if view.hidden_alerts:
        lines += [
            "",
            "## Not drawn, not VALID",
            "",
            "| entity | status | reason |",
            "|---|---|---|",
            *(
                f"| `{_md_cell(ident)}` | {state} | {_md_cell(reason)} |"
                for ident, state, reason in _hidden_rows(view)
            ),
        ]
        if _hidden_more(view):
            lines.append(f"\n… and {_hidden_more(view)} more (`--json` lists every one).")
    return "\n".join(lines) + "\n"


def _comment(value: str) -> str:
    return "%% " + " ".join(value.split()).replace("%", "#37;")


def _mmd(view: GraphView, diagram: str, meta: DocumentMeta) -> str:
    facts = " · ".join(f"{key} {value}" for key, value in _facts(view, meta))
    lines = [_comment(f"{MARKER} · {facts}"), _comment(_summary(view))]
    lines += [
        _comment(f"not drawn: {ident} {state} {reason}")
        for ident, state, reason in _hidden_rows(view)
    ]
    if _hidden_more(view):
        lines.append(_comment(f"not drawn: {_hidden_more(view)} more (--json lists every one)"))
    return "\n".join(lines) + "\n" + diagram


_CSS = """
:root { --ink: #1d2433; --muted: #5b6475; --ground: #fbfbfd; --panel: #ffffff;
  --line: #d9dde6; --accent: #2b6cb0; }
@media (prefers-color-scheme: dark) {
  :root { --ink: #e6e9ef; --muted: #a3abba; --ground: #151922; --panel: #1c2130;
    --line: #2e3546; --accent: #7fb2ee; }
}
body { margin: 0; background: var(--ground); color: var(--ink);
  font: 15px/1.5 system-ui, -apple-system, "Segoe UI", "Noto Sans TC", sans-serif; }
header, main { max-width: 1280px; margin: 0 auto; padding: 16px; }
h1 { font-size: 22px; margin: 8px 0; }
h2 { font-size: 17px; margin: 24px 0 8px; }
.facts, .summary, .note { color: var(--muted); margin: 4px 0; }
code { font: 13px ui-monospace, "Cascadia Code", Consolas, monospace; }
.canvas { overflow: auto; background: var(--panel); border: 1px solid var(--line);
  border-radius: 6px; padding: 12px; }
pre.mermaid { margin: 0; }
table { border-collapse: collapse; margin: 8px 0; }
th, td { border-bottom: 1px solid var(--line); padding: 4px 12px 4px 0; text-align: left;
  vertical-align: top; }
#offline { color: #c0392b; }
"""


def _html_table(header: tuple[str, ...], rows: Iterable[tuple[str, ...]]) -> str:
    head = "".join(f"<th>{html.escape(cell)}</th>" for cell in header)
    body = "".join(
        "<tr>" + "".join(f"<td>{html.escape(cell)}</td>" for cell in row) + "</tr>" for row in rows
    )
    return f"<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table>"


def _html(view: GraphView, diagram: str, meta: DocumentMeta) -> str:
    esc = html.escape
    facts = " · ".join(f"{esc(key)} <code>{esc(value)}</code>" for key, value in _facts(view, meta))
    hidden = ""
    if view.hidden_alerts:
        more = _hidden_more(view)
        hidden = (
            "<h2>Not drawn, not VALID</h2>"
            + _html_table(("entity", "status", "reason"), _hidden_rows(view))
            + (f'<p class="note">… and {more} more (--json lists every one).</p>' if more else "")
        )
    return f"""<!doctype html>
<!-- {MARKER}; regenerate it with the same command instead of editing it -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Provenance graph · {esc(view.scope)}</title>
<style>{_CSS}</style>
</head>
<body>
<header>
<h1>Provenance graph</h1>
<p class="facts">{facts}</p>
<p class="summary">{esc(_summary(view))}</p>
</header>
<main>
<p id="offline" hidden>Mermaid could not be loaded from cdn.jsdelivr.net, so the diagram source is
shown instead. Open this page with network access, or write a .md / .mmd file.</p>
<div class="canvas"><pre class="mermaid">{esc(diagram)}</pre></div>
{hidden}
<h2>Legend</h2>
{_html_table(("mark", "meaning"), _LEGEND)}
<p class="note">{esc(_FOLD_NOTE)}</p>
</main>
<script src="{MERMAID_URL}" integrity="{MERMAID_SRI}" crossorigin="anonymous"></script>
<script>
if (typeof mermaid === "undefined") {{
  document.getElementById("offline").hidden = false;
}} else {{
  const dark = window.matchMedia("(prefers-color-scheme: dark)").matches;
  mermaid.initialize({{
    startOnLoad: false,
    securityLevel: "strict",
    theme: dark ? "dark" : "default",
    maxEdges: {HTML_LIMITS[0]},
    maxTextSize: {HTML_LIMITS[1]},
    flowchart: {{ useMaxWidth: false }},
  }});
  mermaid.run();
}}
</script>
</body>
</html>
"""


_WRITERS: dict[str, Callable[[GraphView, str, DocumentMeta], str]] = {
    "html": _html,
    "md": _markdown,
    "mmd": _mmd,
}


def render_document(view: GraphView, fmt: str, meta: DocumentMeta) -> Document:
    writer = _WRITERS.get(fmt)
    if writer is None:
        raise ValidationFailed(f"unsupported_format: {fmt}; use html, md or mmd")
    diagram = to_mermaid(view)
    max_edges, max_text = HTML_LIMITS if fmt == "html" else DEFAULT_LIMITS
    oversize = len(view.edges) > max_edges or len(diagram) > max_text
    return Document(text=writer(view, diagram, meta), oversize=oversize)


def _inside(path: Path, root: Path) -> bool:
    """``path`` is ``root`` or below it, by spelling or by identity: an extended-length or share
    path can name the data root in text that ``commonpath`` never matches."""
    child, parent = os.path.normcase(str(path)), os.path.normcase(str(root))
    try:
        if os.path.commonpath([child, parent]) == parent:
            return True
    except ValueError:  # different drives, or spellings commonpath cannot compare
        pass
    try:
        home = os.stat(root)
    except OSError:  # a data root that does not exist yet holds nothing
        return False
    if not home.st_ino:  # a volume without file ids (some network drives) cannot say
        return False
    for ancestor in (path, *path.parents):
        try:
            seen = os.stat(ancestor)
        except OSError:  # an ancestor that does not exist yet
            continue
        if (seen.st_dev, seen.st_ino) == (home.st_dev, home.st_ino):
            return True
    return False


def prepare_output(out: Path, data_root: Path) -> tuple[Path, str]:
    """Check ``--out`` before any work: a known suffix, an absolute place outside the data root,
    and either absent or a file this command wrote before. Returns the path and the format."""
    fmt = FORMATS.get(Path(out).suffix.lower())
    if fmt is None:
        raise ValidationFailed(
            f"unsupported_format: {Path(out).suffix or '(none)'}; use .html, .md or .mmd"
        )
    target = Path(out).resolve()
    if not target.is_absolute():  # e.g. a mistyped extended-length prefix on Windows
        raise ValidationFailed(f"out_not_absolute: {out} resolves to {target}")
    if _inside(target, Path(data_root).resolve()):
        raise ValidationFailed(
            f"out_in_data_root: {target}; a drawing is not evidence, write it outside the data root"
        )
    if target.exists():
        if not target.is_file():
            raise ValidationFailed(f"not_a_file: {target}")
        if not _is_ours(target):
            raise ValidationFailed(
                f"exists: {target} was not written by vcp provenance graph; choose another --out"
            )
    return target, fmt


def _is_ours(path: Path) -> bool:
    """The marker must open the file exactly as a writer put it there: a document that merely
    quotes it (this command's own reference page does) is somebody else's. A BOM or CRLF line
    ends added by an editor or git autocrlf do not change whose file it is."""
    with path.open("rb") as handle:
        head = handle.read(_MARKER_WINDOW).decode("utf-8", errors="replace")
    return head.removeprefix("\ufeff").replace("\r\n", "\n").startswith(_SIGNATURES)


def write_document(target: Path, text: str) -> None:
    """Replace ``target`` in one ``os.replace``; a failed write leaves the old file and no temp."""
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.parent / f".{target.name}.{os.urandom(4).hex()}.tmp"
    try:
        with temporary.open("wb") as handle:
            handle.write(text.encode("utf-8"))
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, target)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise
